//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAVItems
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", ConfigurationName="NAVItems.Items_Port")]
    public interface Items_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/items:Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVItems.Read_Result> ReadAsync(NAVItems.Read request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/items:ReadByRecId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVItems.ReadByRecId_Result> ReadByRecIdAsync(NAVItems.ReadByRecId request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/items:ReadMultiple", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVItems.ReadMultiple_Result> ReadMultipleAsync(NAVItems.ReadMultiple request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/items:IsUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVItems.IsUpdated_Result> IsUpdatedAsync(NAVItems.IsUpdated request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/page/items:GetRecIdFromKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NAVItems.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(NAVItems.GetRecIdFromKey request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public partial class Items
    {
        
        private string keyField;
        
        private string noField;
        
        private string user_IDField;
        
        private string descriptionField;
        
        private string description_2Field;
        
        private string description_3Field;
        
        private Type typeField;
        
        private bool typeFieldSpecified;
        
        private bool criticalField;
        
        private bool criticalFieldSpecified;
        
        private decimal inventoryField;
        
        private bool inventoryFieldSpecified;
        
        private bool created_From_Nonstock_ItemField;
        
        private bool created_From_Nonstock_ItemFieldSpecified;
        
        private bool substitutes_ExistField;
        
        private bool substitutes_ExistFieldSpecified;
        
        private bool stockkeeping_Unit_ExistsField;
        
        private bool stockkeeping_Unit_ExistsFieldSpecified;
        
        private bool assembly_BOMField;
        
        private bool assembly_BOMFieldSpecified;
        
        private string production_BOM_NoField;
        
        private string routing_NoField;
        
        private string base_Unit_of_MeasureField;
        
        private string equipment_TypeField;
        
        private Costing_Method costing_MethodField;
        
        private bool costing_MethodFieldSpecified;
        
        private bool cost_is_AdjustedField;
        
        private bool cost_is_AdjustedFieldSpecified;
        
        private decimal standard_CostField;
        
        private bool standard_CostFieldSpecified;
        
        private decimal unit_CostField;
        
        private bool unit_CostFieldSpecified;
        
        private decimal last_Direct_CostField;
        
        private bool last_Direct_CostFieldSpecified;
        
        private Price_Profit_Calculation price_Profit_CalculationField;
        
        private bool price_Profit_CalculationFieldSpecified;
        
        private decimal profit_PercentField;
        
        private bool profit_PercentFieldSpecified;
        
        private decimal unit_PriceField;
        
        private bool unit_PriceFieldSpecified;
        
        private string inventory_Posting_GroupField;
        
        private string gen_Prod_Posting_GroupField;
        
        private string vAT_Prod_Posting_GroupField;
        
        private string item_Disc_GroupField;
        
        private string vendor_NoField;
        
        private string vendor_No_2Field;
        
        private string vendor_Item_NoField;
        
        private string vendor_Item_No_2Field;
        
        private string tariff_NoField;
        
        private string search_DescriptionField;
        
        private decimal overhead_RateField;
        
        private bool overhead_RateFieldSpecified;
        
        private decimal indirect_Cost_PercentField;
        
        private bool indirect_Cost_PercentFieldSpecified;
        
        private decimal purchases_QtyField;
        
        private bool purchases_QtyFieldSpecified;
        
        private decimal maximum_InventoryField;
        
        private bool maximum_InventoryFieldSpecified;
        
        private string item_Category_CodeField;
        
        private decimal reorder_PointField;
        
        private bool reorder_PointFieldSpecified;
        
        private string make_ModelField;
        
        private string wHT_Product_Posting_GroupField;
        
        private decimal purch_Req_Receipt_QtyField;
        
        private bool purch_Req_Receipt_QtyFieldSpecified;
        
        private decimal purch_Req_Release_QtyField;
        
        private bool purch_Req_Release_QtyFieldSpecified;
        
        private decimal negative_Adjmt_QtyField;
        
        private bool negative_Adjmt_QtyFieldSpecified;
        
        private string no_SeriesField;
        
        private string product_Group_CodeField;
        
        private bool blockedField;
        
        private bool blockedFieldSpecified;
        
        private System.DateTime last_Date_ModifiedField;
        
        private bool last_Date_ModifiedFieldSpecified;
        
        private string sales_Unit_of_MeasureField;
        
        private Replenishment_System replenishment_SystemField;
        
        private bool replenishment_SystemFieldSpecified;
        
        private string purch_Unit_of_MeasureField;
        
        private string lead_Time_CalculationField;
        
        private Manufacturing_Policy manufacturing_PolicyField;
        
        private bool manufacturing_PolicyFieldSpecified;
        
        private Flushing_Method flushing_MethodField;
        
        private bool flushing_MethodFieldSpecified;
        
        private Assembly_Policy assembly_PolicyField;
        
        private bool assembly_PolicyFieldSpecified;
        
        private string item_Tracking_CodeField;
        
        private string default_Deferral_Template_CodeField;
        
        private string shelf_NoField;
        
        private string shelf_No_2Field;
        
        private string shelf_No_3Field;
        
        private string location_Modified_byField;
        
        private System.DateTime jmptItmJrnlLines_PostingDateField;
        
        private bool jmptItmJrnlLines_PostingDateFieldSpecified;
        
        private decimal minimum_Order_QuantityField;
        
        private bool minimum_Order_QuantityFieldSpecified;
        
        private decimal maximum_Order_QuantityField;
        
        private bool maximum_Order_QuantityFieldSpecified;
        
        private string tag1Field;
        
        private string tag2Field;
        
        private Item_Tag_Remarks item_Tag_RemarksField;
        
        private bool item_Tag_RemarksFieldSpecified;
        
        private string item_Tag_Updated_ByField;
        
        private System.DateTime item_Tag_DateTimeField;
        
        private bool item_Tag_DateTimeFieldSpecified;
        
        private Item_Tag_Remarks_2 item_Tag_Remarks_2Field;
        
        private bool item_Tag_Remarks_2FieldSpecified;
        
        private string item_Tag_Updated_By_2Field;
        
        private System.DateTime item_Tag_DateTime_2Field;
        
        private bool item_Tag_DateTime_2FieldSpecified;
        
        private string vClassificationField;
        
        private int vIdealLeadTimeField;
        
        private bool vIdealLeadTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string No
        {
            get
            {
                return this.noField;
            }
            set
            {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string User_ID
        {
            get
            {
                return this.user_IDField;
            }
            set
            {
                this.user_IDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Description_2
        {
            get
            {
                return this.description_2Field;
            }
            set
            {
                this.description_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description_3
        {
            get
            {
                return this.description_3Field;
            }
            set
            {
                this.description_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Type Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified
        {
            get
            {
                return this.typeFieldSpecified;
            }
            set
            {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Critical
        {
            get
            {
                return this.criticalField;
            }
            set
            {
                this.criticalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CriticalSpecified
        {
            get
            {
                return this.criticalFieldSpecified;
            }
            set
            {
                this.criticalFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal Inventory
        {
            get
            {
                return this.inventoryField;
            }
            set
            {
                this.inventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventorySpecified
        {
            get
            {
                return this.inventoryFieldSpecified;
            }
            set
            {
                this.inventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Created_From_Nonstock_Item
        {
            get
            {
                return this.created_From_Nonstock_ItemField;
            }
            set
            {
                this.created_From_Nonstock_ItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Created_From_Nonstock_ItemSpecified
        {
            get
            {
                return this.created_From_Nonstock_ItemFieldSpecified;
            }
            set
            {
                this.created_From_Nonstock_ItemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool Substitutes_Exist
        {
            get
            {
                return this.substitutes_ExistField;
            }
            set
            {
                this.substitutes_ExistField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Substitutes_ExistSpecified
        {
            get
            {
                return this.substitutes_ExistFieldSpecified;
            }
            set
            {
                this.substitutes_ExistFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool Stockkeeping_Unit_Exists
        {
            get
            {
                return this.stockkeeping_Unit_ExistsField;
            }
            set
            {
                this.stockkeeping_Unit_ExistsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Stockkeeping_Unit_ExistsSpecified
        {
            get
            {
                return this.stockkeeping_Unit_ExistsFieldSpecified;
            }
            set
            {
                this.stockkeeping_Unit_ExistsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool Assembly_BOM
        {
            get
            {
                return this.assembly_BOMField;
            }
            set
            {
                this.assembly_BOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Assembly_BOMSpecified
        {
            get
            {
                return this.assembly_BOMFieldSpecified;
            }
            set
            {
                this.assembly_BOMFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Production_BOM_No
        {
            get
            {
                return this.production_BOM_NoField;
            }
            set
            {
                this.production_BOM_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Routing_No
        {
            get
            {
                return this.routing_NoField;
            }
            set
            {
                this.routing_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Base_Unit_of_Measure
        {
            get
            {
                return this.base_Unit_of_MeasureField;
            }
            set
            {
                this.base_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Equipment_Type
        {
            get
            {
                return this.equipment_TypeField;
            }
            set
            {
                this.equipment_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public Costing_Method Costing_Method
        {
            get
            {
                return this.costing_MethodField;
            }
            set
            {
                this.costing_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Costing_MethodSpecified
        {
            get
            {
                return this.costing_MethodFieldSpecified;
            }
            set
            {
                this.costing_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool Cost_is_Adjusted
        {
            get
            {
                return this.cost_is_AdjustedField;
            }
            set
            {
                this.cost_is_AdjustedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Cost_is_AdjustedSpecified
        {
            get
            {
                return this.cost_is_AdjustedFieldSpecified;
            }
            set
            {
                this.cost_is_AdjustedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal Standard_Cost
        {
            get
            {
                return this.standard_CostField;
            }
            set
            {
                this.standard_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Standard_CostSpecified
        {
            get
            {
                return this.standard_CostFieldSpecified;
            }
            set
            {
                this.standard_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal Unit_Cost
        {
            get
            {
                return this.unit_CostField;
            }
            set
            {
                this.unit_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_CostSpecified
        {
            get
            {
                return this.unit_CostFieldSpecified;
            }
            set
            {
                this.unit_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal Last_Direct_Cost
        {
            get
            {
                return this.last_Direct_CostField;
            }
            set
            {
                this.last_Direct_CostField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Direct_CostSpecified
        {
            get
            {
                return this.last_Direct_CostFieldSpecified;
            }
            set
            {
                this.last_Direct_CostFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public Price_Profit_Calculation Price_Profit_Calculation
        {
            get
            {
                return this.price_Profit_CalculationField;
            }
            set
            {
                this.price_Profit_CalculationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Price_Profit_CalculationSpecified
        {
            get
            {
                return this.price_Profit_CalculationFieldSpecified;
            }
            set
            {
                this.price_Profit_CalculationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal Profit_Percent
        {
            get
            {
                return this.profit_PercentField;
            }
            set
            {
                this.profit_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Profit_PercentSpecified
        {
            get
            {
                return this.profit_PercentFieldSpecified;
            }
            set
            {
                this.profit_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public decimal Unit_Price
        {
            get
            {
                return this.unit_PriceField;
            }
            set
            {
                this.unit_PriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unit_PriceSpecified
        {
            get
            {
                return this.unit_PriceFieldSpecified;
            }
            set
            {
                this.unit_PriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string Inventory_Posting_Group
        {
            get
            {
                return this.inventory_Posting_GroupField;
            }
            set
            {
                this.inventory_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string Gen_Prod_Posting_Group
        {
            get
            {
                return this.gen_Prod_Posting_GroupField;
            }
            set
            {
                this.gen_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string VAT_Prod_Posting_Group
        {
            get
            {
                return this.vAT_Prod_Posting_GroupField;
            }
            set
            {
                this.vAT_Prod_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Item_Disc_Group
        {
            get
            {
                return this.item_Disc_GroupField;
            }
            set
            {
                this.item_Disc_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string Vendor_No
        {
            get
            {
                return this.vendor_NoField;
            }
            set
            {
                this.vendor_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Vendor_No_2
        {
            get
            {
                return this.vendor_No_2Field;
            }
            set
            {
                this.vendor_No_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Vendor_Item_No
        {
            get
            {
                return this.vendor_Item_NoField;
            }
            set
            {
                this.vendor_Item_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Vendor_Item_No_2
        {
            get
            {
                return this.vendor_Item_No_2Field;
            }
            set
            {
                this.vendor_Item_No_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string Tariff_No
        {
            get
            {
                return this.tariff_NoField;
            }
            set
            {
                this.tariff_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string Search_Description
        {
            get
            {
                return this.search_DescriptionField;
            }
            set
            {
                this.search_DescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public decimal Overhead_Rate
        {
            get
            {
                return this.overhead_RateField;
            }
            set
            {
                this.overhead_RateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Overhead_RateSpecified
        {
            get
            {
                return this.overhead_RateFieldSpecified;
            }
            set
            {
                this.overhead_RateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public decimal Indirect_Cost_Percent
        {
            get
            {
                return this.indirect_Cost_PercentField;
            }
            set
            {
                this.indirect_Cost_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Indirect_Cost_PercentSpecified
        {
            get
            {
                return this.indirect_Cost_PercentFieldSpecified;
            }
            set
            {
                this.indirect_Cost_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public decimal Purchases_Qty
        {
            get
            {
                return this.purchases_QtyField;
            }
            set
            {
                this.purchases_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purchases_QtySpecified
        {
            get
            {
                return this.purchases_QtyFieldSpecified;
            }
            set
            {
                this.purchases_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public decimal Maximum_Inventory
        {
            get
            {
                return this.maximum_InventoryField;
            }
            set
            {
                this.maximum_InventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_InventorySpecified
        {
            get
            {
                return this.maximum_InventoryFieldSpecified;
            }
            set
            {
                this.maximum_InventoryFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string Item_Category_Code
        {
            get
            {
                return this.item_Category_CodeField;
            }
            set
            {
                this.item_Category_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public decimal Reorder_Point
        {
            get
            {
                return this.reorder_PointField;
            }
            set
            {
                this.reorder_PointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Reorder_PointSpecified
        {
            get
            {
                return this.reorder_PointFieldSpecified;
            }
            set
            {
                this.reorder_PointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string Make_Model
        {
            get
            {
                return this.make_ModelField;
            }
            set
            {
                this.make_ModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string WHT_Product_Posting_Group
        {
            get
            {
                return this.wHT_Product_Posting_GroupField;
            }
            set
            {
                this.wHT_Product_Posting_GroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public decimal Purch_Req_Receipt_Qty
        {
            get
            {
                return this.purch_Req_Receipt_QtyField;
            }
            set
            {
                this.purch_Req_Receipt_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purch_Req_Receipt_QtySpecified
        {
            get
            {
                return this.purch_Req_Receipt_QtyFieldSpecified;
            }
            set
            {
                this.purch_Req_Receipt_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public decimal Purch_Req_Release_Qty
        {
            get
            {
                return this.purch_Req_Release_QtyField;
            }
            set
            {
                this.purch_Req_Release_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Purch_Req_Release_QtySpecified
        {
            get
            {
                return this.purch_Req_Release_QtyFieldSpecified;
            }
            set
            {
                this.purch_Req_Release_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public decimal Negative_Adjmt_Qty
        {
            get
            {
                return this.negative_Adjmt_QtyField;
            }
            set
            {
                this.negative_Adjmt_QtyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Negative_Adjmt_QtySpecified
        {
            get
            {
                return this.negative_Adjmt_QtyFieldSpecified;
            }
            set
            {
                this.negative_Adjmt_QtyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string No_Series
        {
            get
            {
                return this.no_SeriesField;
            }
            set
            {
                this.no_SeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string Product_Group_Code
        {
            get
            {
                return this.product_Group_CodeField;
            }
            set
            {
                this.product_Group_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public bool Blocked
        {
            get
            {
                return this.blockedField;
            }
            set
            {
                this.blockedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BlockedSpecified
        {
            get
            {
                return this.blockedFieldSpecified;
            }
            set
            {
                this.blockedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=49)]
        public System.DateTime Last_Date_Modified
        {
            get
            {
                return this.last_Date_ModifiedField;
            }
            set
            {
                this.last_Date_ModifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Last_Date_ModifiedSpecified
        {
            get
            {
                return this.last_Date_ModifiedFieldSpecified;
            }
            set
            {
                this.last_Date_ModifiedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string Sales_Unit_of_Measure
        {
            get
            {
                return this.sales_Unit_of_MeasureField;
            }
            set
            {
                this.sales_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public Replenishment_System Replenishment_System
        {
            get
            {
                return this.replenishment_SystemField;
            }
            set
            {
                this.replenishment_SystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Replenishment_SystemSpecified
        {
            get
            {
                return this.replenishment_SystemFieldSpecified;
            }
            set
            {
                this.replenishment_SystemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string Purch_Unit_of_Measure
        {
            get
            {
                return this.purch_Unit_of_MeasureField;
            }
            set
            {
                this.purch_Unit_of_MeasureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string Lead_Time_Calculation
        {
            get
            {
                return this.lead_Time_CalculationField;
            }
            set
            {
                this.lead_Time_CalculationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public Manufacturing_Policy Manufacturing_Policy
        {
            get
            {
                return this.manufacturing_PolicyField;
            }
            set
            {
                this.manufacturing_PolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Manufacturing_PolicySpecified
        {
            get
            {
                return this.manufacturing_PolicyFieldSpecified;
            }
            set
            {
                this.manufacturing_PolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public Flushing_Method Flushing_Method
        {
            get
            {
                return this.flushing_MethodField;
            }
            set
            {
                this.flushing_MethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Flushing_MethodSpecified
        {
            get
            {
                return this.flushing_MethodFieldSpecified;
            }
            set
            {
                this.flushing_MethodFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public Assembly_Policy Assembly_Policy
        {
            get
            {
                return this.assembly_PolicyField;
            }
            set
            {
                this.assembly_PolicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Assembly_PolicySpecified
        {
            get
            {
                return this.assembly_PolicyFieldSpecified;
            }
            set
            {
                this.assembly_PolicyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string Item_Tracking_Code
        {
            get
            {
                return this.item_Tracking_CodeField;
            }
            set
            {
                this.item_Tracking_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string Default_Deferral_Template_Code
        {
            get
            {
                return this.default_Deferral_Template_CodeField;
            }
            set
            {
                this.default_Deferral_Template_CodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string Shelf_No
        {
            get
            {
                return this.shelf_NoField;
            }
            set
            {
                this.shelf_NoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string Shelf_No_2
        {
            get
            {
                return this.shelf_No_2Field;
            }
            set
            {
                this.shelf_No_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string Shelf_No_3
        {
            get
            {
                return this.shelf_No_3Field;
            }
            set
            {
                this.shelf_No_3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string Location_Modified_by
        {
            get
            {
                return this.location_Modified_byField;
            }
            set
            {
                this.location_Modified_byField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=63)]
        public System.DateTime jmptItmJrnlLines_PostingDate
        {
            get
            {
                return this.jmptItmJrnlLines_PostingDateField;
            }
            set
            {
                this.jmptItmJrnlLines_PostingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool jmptItmJrnlLines_PostingDateSpecified
        {
            get
            {
                return this.jmptItmJrnlLines_PostingDateFieldSpecified;
            }
            set
            {
                this.jmptItmJrnlLines_PostingDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public decimal Minimum_Order_Quantity
        {
            get
            {
                return this.minimum_Order_QuantityField;
            }
            set
            {
                this.minimum_Order_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Minimum_Order_QuantitySpecified
        {
            get
            {
                return this.minimum_Order_QuantityFieldSpecified;
            }
            set
            {
                this.minimum_Order_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public decimal Maximum_Order_Quantity
        {
            get
            {
                return this.maximum_Order_QuantityField;
            }
            set
            {
                this.maximum_Order_QuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Maximum_Order_QuantitySpecified
        {
            get
            {
                return this.maximum_Order_QuantityFieldSpecified;
            }
            set
            {
                this.maximum_Order_QuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public string tag1
        {
            get
            {
                return this.tag1Field;
            }
            set
            {
                this.tag1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string tag2
        {
            get
            {
                return this.tag2Field;
            }
            set
            {
                this.tag2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public Item_Tag_Remarks Item_Tag_Remarks
        {
            get
            {
                return this.item_Tag_RemarksField;
            }
            set
            {
                this.item_Tag_RemarksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Item_Tag_RemarksSpecified
        {
            get
            {
                return this.item_Tag_RemarksFieldSpecified;
            }
            set
            {
                this.item_Tag_RemarksFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string Item_Tag_Updated_By
        {
            get
            {
                return this.item_Tag_Updated_ByField;
            }
            set
            {
                this.item_Tag_Updated_ByField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public System.DateTime Item_Tag_DateTime
        {
            get
            {
                return this.item_Tag_DateTimeField;
            }
            set
            {
                this.item_Tag_DateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Item_Tag_DateTimeSpecified
        {
            get
            {
                return this.item_Tag_DateTimeFieldSpecified;
            }
            set
            {
                this.item_Tag_DateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=71)]
        public Item_Tag_Remarks_2 Item_Tag_Remarks_2
        {
            get
            {
                return this.item_Tag_Remarks_2Field;
            }
            set
            {
                this.item_Tag_Remarks_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Item_Tag_Remarks_2Specified
        {
            get
            {
                return this.item_Tag_Remarks_2FieldSpecified;
            }
            set
            {
                this.item_Tag_Remarks_2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public string Item_Tag_Updated_By_2
        {
            get
            {
                return this.item_Tag_Updated_By_2Field;
            }
            set
            {
                this.item_Tag_Updated_By_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public System.DateTime Item_Tag_DateTime_2
        {
            get
            {
                return this.item_Tag_DateTime_2Field;
            }
            set
            {
                this.item_Tag_DateTime_2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Item_Tag_DateTime_2Specified
        {
            get
            {
                return this.item_Tag_DateTime_2FieldSpecified;
            }
            set
            {
                this.item_Tag_DateTime_2FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string vClassification
        {
            get
            {
                return this.vClassificationField;
            }
            set
            {
                this.vClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public int vIdealLeadTime
        {
            get
            {
                return this.vIdealLeadTimeField;
            }
            set
            {
                this.vIdealLeadTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vIdealLeadTimeSpecified
        {
            get
            {
                return this.vIdealLeadTimeFieldSpecified;
            }
            set
            {
                this.vIdealLeadTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Type
    {
        
        /// <remarks/>
        Inventory,
        
        /// <remarks/>
        Service,
        
        /// <remarks/>
        Non_Inventory,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Costing_Method
    {
        
        /// <remarks/>
        FIFO,
        
        /// <remarks/>
        LIFO,
        
        /// <remarks/>
        Specific,
        
        /// <remarks/>
        Average,
        
        /// <remarks/>
        Standard,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Price_Profit_Calculation
    {
        
        /// <remarks/>
        Profit_x003D_Price_Cost,
        
        /// <remarks/>
        Price_x003D_Cost_x002B_Profit,
        
        /// <remarks/>
        No_Relationship,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Replenishment_System
    {
        
        /// <remarks/>
        Purchase,
        
        /// <remarks/>
        Prod_Order,
        
        /// <remarks/>
        Assembly,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Manufacturing_Policy
    {
        
        /// <remarks/>
        Make_to_Stock,
        
        /// <remarks/>
        Make_to_Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Flushing_Method
    {
        
        /// <remarks/>
        Manual,
        
        /// <remarks/>
        Forward,
        
        /// <remarks/>
        Backward,
        
        /// <remarks/>
        Pick__x002B__Forward,
        
        /// <remarks/>
        Pick__x002B__Backward,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Assembly_Policy
    {
        
        /// <remarks/>
        Assemble_to_Stock,
        
        /// <remarks/>
        Assemble_to_Order,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Item_Tag_Remarks
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Obsolete,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Wrong_Product_Group_Code,
        
        /// <remarks/>
        Others,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Item_Tag_Remarks_2
    {
        
        /// <remarks/>
        _blank_,
        
        /// <remarks/>
        Obsolete,
        
        /// <remarks/>
        Duplicate,
        
        /// <remarks/>
        Wrong_Product_Group_Code,
        
        /// <remarks/>
        Others,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public partial class Items_Filter
    {
        
        private Items_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Items_Fields Field
        {
            get
            {
                return this.fieldField;
            }
            set
            {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Criteria
        {
            get
            {
                return this.criteriaField;
            }
            set
            {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items")]
    public enum Items_Fields
    {
        
        /// <remarks/>
        No,
        
        /// <remarks/>
        User_ID,
        
        /// <remarks/>
        Description,
        
        /// <remarks/>
        Description_2,
        
        /// <remarks/>
        Description_3,
        
        /// <remarks/>
        Type,
        
        /// <remarks/>
        Critical,
        
        /// <remarks/>
        Inventory,
        
        /// <remarks/>
        Created_From_Nonstock_Item,
        
        /// <remarks/>
        Substitutes_Exist,
        
        /// <remarks/>
        Stockkeeping_Unit_Exists,
        
        /// <remarks/>
        Assembly_BOM,
        
        /// <remarks/>
        Production_BOM_No,
        
        /// <remarks/>
        Routing_No,
        
        /// <remarks/>
        Base_Unit_of_Measure,
        
        /// <remarks/>
        Equipment_Type,
        
        /// <remarks/>
        Costing_Method,
        
        /// <remarks/>
        Cost_is_Adjusted,
        
        /// <remarks/>
        Standard_Cost,
        
        /// <remarks/>
        Unit_Cost,
        
        /// <remarks/>
        Last_Direct_Cost,
        
        /// <remarks/>
        Price_Profit_Calculation,
        
        /// <remarks/>
        Profit_Percent,
        
        /// <remarks/>
        Unit_Price,
        
        /// <remarks/>
        Inventory_Posting_Group,
        
        /// <remarks/>
        Gen_Prod_Posting_Group,
        
        /// <remarks/>
        VAT_Prod_Posting_Group,
        
        /// <remarks/>
        Item_Disc_Group,
        
        /// <remarks/>
        Vendor_No,
        
        /// <remarks/>
        Vendor_No_2,
        
        /// <remarks/>
        Vendor_Item_No,
        
        /// <remarks/>
        Vendor_Item_No_2,
        
        /// <remarks/>
        Tariff_No,
        
        /// <remarks/>
        Search_Description,
        
        /// <remarks/>
        Overhead_Rate,
        
        /// <remarks/>
        Indirect_Cost_Percent,
        
        /// <remarks/>
        Purchases_Qty,
        
        /// <remarks/>
        Maximum_Inventory,
        
        /// <remarks/>
        Item_Category_Code,
        
        /// <remarks/>
        Reorder_Point,
        
        /// <remarks/>
        Make_Model,
        
        /// <remarks/>
        WHT_Product_Posting_Group,
        
        /// <remarks/>
        Purch_Req_Receipt_Qty,
        
        /// <remarks/>
        Purch_Req_Release_Qty,
        
        /// <remarks/>
        Negative_Adjmt_Qty,
        
        /// <remarks/>
        No_Series,
        
        /// <remarks/>
        Product_Group_Code,
        
        /// <remarks/>
        Blocked,
        
        /// <remarks/>
        Last_Date_Modified,
        
        /// <remarks/>
        Sales_Unit_of_Measure,
        
        /// <remarks/>
        Replenishment_System,
        
        /// <remarks/>
        Purch_Unit_of_Measure,
        
        /// <remarks/>
        Lead_Time_Calculation,
        
        /// <remarks/>
        Manufacturing_Policy,
        
        /// <remarks/>
        Flushing_Method,
        
        /// <remarks/>
        Assembly_Policy,
        
        /// <remarks/>
        Item_Tracking_Code,
        
        /// <remarks/>
        Default_Deferral_Template_Code,
        
        /// <remarks/>
        Shelf_No,
        
        /// <remarks/>
        Shelf_No_2,
        
        /// <remarks/>
        Shelf_No_3,
        
        /// <remarks/>
        Location_Modified_by,
        
        /// <remarks/>
        jmptItmJrnlLines_PostingDate,
        
        /// <remarks/>
        Minimum_Order_Quantity,
        
        /// <remarks/>
        Maximum_Order_Quantity,
        
        /// <remarks/>
        tag1,
        
        /// <remarks/>
        tag2,
        
        /// <remarks/>
        Item_Tag_Remarks,
        
        /// <remarks/>
        Item_Tag_Updated_By,
        
        /// <remarks/>
        Item_Tag_DateTime,
        
        /// <remarks/>
        Item_Tag_Remarks_2,
        
        /// <remarks/>
        Item_Tag_Updated_By_2,
        
        /// <remarks/>
        Item_Tag_DateTime_2,
        
        /// <remarks/>
        vClassification,
        
        /// <remarks/>
        vIdealLeadTime,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class Read
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public string No;
        
        public Read()
        {
        }
        
        public Read(string No)
        {
            this.No = No;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Read_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class Read_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public NAVItems.Items Items;
        
        public Read_Result()
        {
        }
        
        public Read_Result(NAVItems.Items Items)
        {
            this.Items = Items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class ReadByRecId
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public string recId;
        
        public ReadByRecId()
        {
        }
        
        public ReadByRecId(string recId)
        {
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadByRecId_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class ReadByRecId_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public NAVItems.Items Items;
        
        public ReadByRecId_Result()
        {
        }
        
        public ReadByRecId_Result(NAVItems.Items Items)
        {
            this.Items = Items;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class ReadMultiple
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("filter")]
        public NAVItems.Items_Filter[] filter;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=1)]
        public string bookmarkKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=2)]
        public int setSize;
        
        public ReadMultiple()
        {
        }
        
        public ReadMultiple(NAVItems.Items_Filter[] filter, string bookmarkKey, int setSize)
        {
            this.filter = filter;
            this.bookmarkKey = bookmarkKey;
            this.setSize = setSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReadMultiple_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class ReadMultiple_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadMultiple_Result", Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public NAVItems.Items[] ReadMultiple_Result1;
        
        public ReadMultiple_Result()
        {
        }
        
        public ReadMultiple_Result(NAVItems.Items[] ReadMultiple_Result1)
        {
            this.ReadMultiple_Result1 = ReadMultiple_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class IsUpdated
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public string Key;
        
        public IsUpdated()
        {
        }
        
        public IsUpdated(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsUpdated_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class IsUpdated_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsUpdated_Result", Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public bool IsUpdated_Result1;
        
        public IsUpdated_Result()
        {
        }
        
        public IsUpdated_Result(bool IsUpdated_Result1)
        {
            this.IsUpdated_Result1 = IsUpdated_Result1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class GetRecIdFromKey
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public string Key;
        
        public GetRecIdFromKey()
        {
        }
        
        public GetRecIdFromKey(string Key)
        {
            this.Key = Key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecIdFromKey_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/page/items", IsWrapped=true)]
    public partial class GetRecIdFromKey_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRecIdFromKey_Result", Namespace="urn:microsoft-dynamics-schemas/page/items", Order=0)]
        public string GetRecIdFromKey_Result1;
        
        public GetRecIdFromKey_Result()
        {
        }
        
        public GetRecIdFromKey_Result(string GetRecIdFromKey_Result1)
        {
            this.GetRecIdFromKey_Result1 = GetRecIdFromKey_Result1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface Items_PortChannel : NAVItems.Items_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class Items_PortClient : System.ServiceModel.ClientBase<NAVItems.Items_Port>, NAVItems.Items_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Items_PortClient() : 
                base(Items_PortClient.GetDefaultBinding(), Items_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.Items_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Items_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(Items_PortClient.GetBindingForEndpoint(endpointConfiguration), Items_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Items_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Items_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Items_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Items_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Items_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVItems.Read_Result> NAVItems.Items_Port.ReadAsync(NAVItems.Read request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVItems.Read_Result> ReadAsync(string No)
        {
            NAVItems.Read inValue = new NAVItems.Read();
            inValue.No = No;
            return ((NAVItems.Items_Port)(this)).ReadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVItems.ReadByRecId_Result> NAVItems.Items_Port.ReadByRecIdAsync(NAVItems.ReadByRecId request)
        {
            return base.Channel.ReadByRecIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVItems.ReadByRecId_Result> ReadByRecIdAsync(string recId)
        {
            NAVItems.ReadByRecId inValue = new NAVItems.ReadByRecId();
            inValue.recId = recId;
            return ((NAVItems.Items_Port)(this)).ReadByRecIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVItems.ReadMultiple_Result> NAVItems.Items_Port.ReadMultipleAsync(NAVItems.ReadMultiple request)
        {
            return base.Channel.ReadMultipleAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVItems.ReadMultiple_Result> ReadMultipleAsync(NAVItems.Items_Filter[] filter, string bookmarkKey, int setSize)
        {
            NAVItems.ReadMultiple inValue = new NAVItems.ReadMultiple();
            inValue.filter = filter;
            inValue.bookmarkKey = bookmarkKey;
            inValue.setSize = setSize;
            return ((NAVItems.Items_Port)(this)).ReadMultipleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVItems.IsUpdated_Result> NAVItems.Items_Port.IsUpdatedAsync(NAVItems.IsUpdated request)
        {
            return base.Channel.IsUpdatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVItems.IsUpdated_Result> IsUpdatedAsync(string Key)
        {
            NAVItems.IsUpdated inValue = new NAVItems.IsUpdated();
            inValue.Key = Key;
            return ((NAVItems.Items_Port)(this)).IsUpdatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NAVItems.GetRecIdFromKey_Result> NAVItems.Items_Port.GetRecIdFromKeyAsync(NAVItems.GetRecIdFromKey request)
        {
            return base.Channel.GetRecIdFromKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<NAVItems.GetRecIdFromKey_Result> GetRecIdFromKeyAsync(string Key)
        {
            NAVItems.GetRecIdFromKey inValue = new NAVItems.GetRecIdFromKey();
            inValue.Key = Key;
            return ((NAVItems.Items_Port)(this)).GetRecIdFromKeyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Items_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Items_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://aprodite.semiraramining.net:7057/BC130_SMPC_TEST/WS/Semirara/Page/Items");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Items_PortClient.GetBindingForEndpoint(EndpointConfiguration.Items_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Items_PortClient.GetEndpointAddress(EndpointConfiguration.Items_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            Items_Port,
        }
    }
}
