//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavCU
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", ConfigurationName="NavCU.FODL_Web_Service_Port")]
    public interface FODL_Web_Service_Port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:DownloadDepartment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.DownloadDepartment_Result> DownloadDepartmentAsync(NavCU.DownloadDepartment request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:UploadToNavision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.UploadToNavision_Result> UploadToNavisionAsync(NavCU.UploadToNavision request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:ValidateShortcutDimCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.ValidateShortcutDimCode_Result> ValidateShortcutDimCodeAsync(NavCU.ValidateShortcutDimCode request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:AssignNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.AssignNo_Result> AssignNoAsync(NavCU.AssignNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:GetDocumentNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.GetDocumentNo_Result> GetDocumentNoAsync(NavCU.GetDocumentNo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:NewBatchName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.NewBatchName_Result> NewBatchNameAsync(NavCU.NewBatchName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:DownloadItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.DownloadItems_Result> DownloadItemsAsync(NavCU.DownloadItems request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service:DownloadEquipments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<NavCU.DownloadEquipments_Result> DownloadEquipmentsAsync(NavCU.DownloadEquipments request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadDepartment", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class DownloadDepartment
    {
        
        public DownloadDepartment()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadDepartment_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class DownloadDepartment_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public DownloadDepartment_Result()
        {
        }
        
        public DownloadDepartment_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadToNavision", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class UploadToNavision
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string batchNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=1)]
        public int lineNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=2)]
        public string itemNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime postingDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime documentDate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=5)]
        public int qtyRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=6)]
        public string equipmentNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=7)]
        public string officeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=8)]
        public string fuelCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=9)]
        public string locationCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=10)]
        public string deptCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=11)]
        public string documentNo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=12)]
        public string jobCardNo;
        
        public UploadToNavision()
        {
        }
        
        public UploadToNavision(string batchNo, int lineNo, string itemNo, System.DateTime postingDate, System.DateTime documentDate, int qtyRequest, string equipmentNo, string officeCode, string fuelCode, string locationCode, string deptCode, string documentNo, string jobCardNo)
        {
            this.batchNo = batchNo;
            this.lineNo = lineNo;
            this.itemNo = itemNo;
            this.postingDate = postingDate;
            this.documentDate = documentDate;
            this.qtyRequest = qtyRequest;
            this.equipmentNo = equipmentNo;
            this.officeCode = officeCode;
            this.fuelCode = fuelCode;
            this.locationCode = locationCode;
            this.deptCode = deptCode;
            this.documentNo = documentNo;
            this.jobCardNo = jobCardNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadToNavision_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class UploadToNavision_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public UploadToNavision_Result()
        {
        }
        
        public UploadToNavision_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateShortcutDimCode", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class ValidateShortcutDimCode
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public int fieldNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=1)]
        public string shortcutDimCode;
        
        public ValidateShortcutDimCode()
        {
        }
        
        public ValidateShortcutDimCode(int fieldNumber, string shortcutDimCode)
        {
            this.fieldNumber = fieldNumber;
            this.shortcutDimCode = shortcutDimCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ValidateShortcutDimCode_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class ValidateShortcutDimCode_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string shortcutDimCode;
        
        public ValidateShortcutDimCode_Result()
        {
        }
        
        public ValidateShortcutDimCode_Result(string shortcutDimCode)
        {
            this.shortcutDimCode = shortcutDimCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignNo", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class AssignNo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string vNoSeries;
        
        public AssignNo()
        {
        }
        
        public AssignNo(string vNoSeries)
        {
            this.vNoSeries = vNoSeries;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AssignNo_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class AssignNo_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public AssignNo_Result()
        {
        }
        
        public AssignNo_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentNo", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class GetDocumentNo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string batchNo;
        
        public GetDocumentNo()
        {
        }
        
        public GetDocumentNo(string batchNo)
        {
            this.batchNo = batchNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDocumentNo_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class GetDocumentNo_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public GetDocumentNo_Result()
        {
        }
        
        public GetDocumentNo_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewBatchName", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class NewBatchName
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string batchNo;
        
        public NewBatchName()
        {
        }
        
        public NewBatchName(string batchNo)
        {
            this.batchNo = batchNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="NewBatchName_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class NewBatchName_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public NewBatchName_Result()
        {
        }
        
        public NewBatchName_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadItems", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class DownloadItems
    {
        
        public DownloadItems()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadItems_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class DownloadItems_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public DownloadItems_Result()
        {
        }
        
        public DownloadItems_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadEquipments", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class DownloadEquipments
    {
        
        public DownloadEquipments()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadEquipments_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", IsWrapped=true)]
    public partial class DownloadEquipments_Result
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/FODL_Web_Service", Order=0)]
        public string return_value;
        
        public DownloadEquipments_Result()
        {
        }
        
        public DownloadEquipments_Result(string return_value)
        {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface FODL_Web_Service_PortChannel : NavCU.FODL_Web_Service_Port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class FODL_Web_Service_PortClient : System.ServiceModel.ClientBase<NavCU.FODL_Web_Service_Port>, NavCU.FODL_Web_Service_Port
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FODL_Web_Service_PortClient() : 
                base(FODL_Web_Service_PortClient.GetDefaultBinding(), FODL_Web_Service_PortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.FODL_Web_Service_Port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FODL_Web_Service_PortClient(EndpointConfiguration endpointConfiguration) : 
                base(FODL_Web_Service_PortClient.GetBindingForEndpoint(endpointConfiguration), FODL_Web_Service_PortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FODL_Web_Service_PortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FODL_Web_Service_PortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FODL_Web_Service_PortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FODL_Web_Service_PortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FODL_Web_Service_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.DownloadDepartment_Result> NavCU.FODL_Web_Service_Port.DownloadDepartmentAsync(NavCU.DownloadDepartment request)
        {
            return base.Channel.DownloadDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.DownloadDepartment_Result> DownloadDepartmentAsync()
        {
            NavCU.DownloadDepartment inValue = new NavCU.DownloadDepartment();
            return ((NavCU.FODL_Web_Service_Port)(this)).DownloadDepartmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.UploadToNavision_Result> NavCU.FODL_Web_Service_Port.UploadToNavisionAsync(NavCU.UploadToNavision request)
        {
            return base.Channel.UploadToNavisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.UploadToNavision_Result> UploadToNavisionAsync(string batchNo, int lineNo, string itemNo, System.DateTime postingDate, System.DateTime documentDate, int qtyRequest, string equipmentNo, string officeCode, string fuelCode, string locationCode, string deptCode, string documentNo, string jobCardNo)
        {
            NavCU.UploadToNavision inValue = new NavCU.UploadToNavision();
            inValue.batchNo = batchNo;
            inValue.lineNo = lineNo;
            inValue.itemNo = itemNo;
            inValue.postingDate = postingDate;
            inValue.documentDate = documentDate;
            inValue.qtyRequest = qtyRequest;
            inValue.equipmentNo = equipmentNo;
            inValue.officeCode = officeCode;
            inValue.fuelCode = fuelCode;
            inValue.locationCode = locationCode;
            inValue.deptCode = deptCode;
            inValue.documentNo = documentNo;
            inValue.jobCardNo = jobCardNo;
            return ((NavCU.FODL_Web_Service_Port)(this)).UploadToNavisionAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<NavCU.ValidateShortcutDimCode_Result> ValidateShortcutDimCodeAsync(NavCU.ValidateShortcutDimCode request)
        {
            return base.Channel.ValidateShortcutDimCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.AssignNo_Result> NavCU.FODL_Web_Service_Port.AssignNoAsync(NavCU.AssignNo request)
        {
            return base.Channel.AssignNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.AssignNo_Result> AssignNoAsync(string vNoSeries)
        {
            NavCU.AssignNo inValue = new NavCU.AssignNo();
            inValue.vNoSeries = vNoSeries;
            return ((NavCU.FODL_Web_Service_Port)(this)).AssignNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.GetDocumentNo_Result> NavCU.FODL_Web_Service_Port.GetDocumentNoAsync(NavCU.GetDocumentNo request)
        {
            return base.Channel.GetDocumentNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.GetDocumentNo_Result> GetDocumentNoAsync(string batchNo)
        {
            NavCU.GetDocumentNo inValue = new NavCU.GetDocumentNo();
            inValue.batchNo = batchNo;
            return ((NavCU.FODL_Web_Service_Port)(this)).GetDocumentNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.NewBatchName_Result> NavCU.FODL_Web_Service_Port.NewBatchNameAsync(NavCU.NewBatchName request)
        {
            return base.Channel.NewBatchNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.NewBatchName_Result> NewBatchNameAsync(string batchNo)
        {
            NavCU.NewBatchName inValue = new NavCU.NewBatchName();
            inValue.batchNo = batchNo;
            return ((NavCU.FODL_Web_Service_Port)(this)).NewBatchNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.DownloadItems_Result> NavCU.FODL_Web_Service_Port.DownloadItemsAsync(NavCU.DownloadItems request)
        {
            return base.Channel.DownloadItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.DownloadItems_Result> DownloadItemsAsync()
        {
            NavCU.DownloadItems inValue = new NavCU.DownloadItems();
            return ((NavCU.FODL_Web_Service_Port)(this)).DownloadItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NavCU.DownloadEquipments_Result> NavCU.FODL_Web_Service_Port.DownloadEquipmentsAsync(NavCU.DownloadEquipments request)
        {
            return base.Channel.DownloadEquipmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<NavCU.DownloadEquipments_Result> DownloadEquipmentsAsync()
        {
            NavCU.DownloadEquipments inValue = new NavCU.DownloadEquipments();
            return ((NavCU.FODL_Web_Service_Port)(this)).DownloadEquipmentsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FODL_Web_Service_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.FODL_Web_Service_Port))
            {
                return new System.ServiceModel.EndpointAddress("http://aprodite.semiraramining.net:7057/BC130_SMPC_TEST/WS/Semirara/Codeunit/FODL" +
                        "_Web_Service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FODL_Web_Service_PortClient.GetBindingForEndpoint(EndpointConfiguration.FODL_Web_Service_Port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FODL_Web_Service_PortClient.GetEndpointAddress(EndpointConfiguration.FODL_Web_Service_Port);
        }
        
        public enum EndpointConfiguration
        {
            
            FODL_Web_Service_Port,
        }
    }
}
